version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    env_file:
      - ./src/.env.production
